config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index", as: :tasks

  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update", as: :task_update

  get "tasks/new", to: "tasks#new", as: :task_new
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: :task

  delete "tasks/:id", to: "tasks#destroy", as: :task_delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:id, :title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>To do list</h2>
<ul>
<% @tasks.each do |task| %>
  <li>
</h2><%= link_to task.title, task_path(task) %><h2>
  </li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Name: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Description: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit">
</form>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "All the tasks", tasks_path %>

<%= link_to "Edit task", task_edit_path %>

<%= link_to "DELETE", task_delete_path, method: :delete, data: {confirm: "are you sure?"} %>